### PR TITLE
deploy the type document

### LINKED ISSUE #63: Deploy the type document
## Feature Description

Deploy a type document of the backend main function.

## Why is this feature important?

For the reference of implementation.

## Additional Context

Automation required.

### PR DESCRIPTION
**Pull request by hitohata**
## Overviews of implementation

Added a document deploy action.
Updated a test action.

## Review points

I decided to change the directory depending on the branches. When the main branch, the document is deployed to the prod directory, and when the develop branch, the document is deployed to the dev directory.
The type doc, under the dev or prod, is nested to "/backend/main/typedoc". But I'm not sure if it is good or not. Is it too long?

### CODE REVIEW

**Review by taniguchiiqqq — APPROVED** [review]
I just ensured the docker-compose.yaml works. we'll see if the action works well after merging.
> I decided to change the directory depending on the branches. When the main branch, the document is deployed to the prod directory, and when the develop branch, the document is deployed to the dev directory.

Thank you! I love this way. Our doc is getting like for the real product.

> The type doc, under the dev or prod, is nested to "/backend/main/typedoc". But I'm not sure if it is good or not. Is it too long?

The idea I came up with is only making it "/backend/main/", if you don't intend to make another doc for main system.

**Comment by hitohata** [comment]
@taniguchiiqqq 
Thank you for reviewing.
> The idea I came up with is only making it "/backend/main/", if you don't intend to make another doc for main system.

Actually, I think we need the API docs for each endpoint, so I set the directory like this. But for now, it hasn't been decided yet, so I fixed the directory structure.

**Comment by taniguchiiqqq** [comment]
@hitohata 
Thank you for telling your thought! but Sorry, maybe I'm misunderstanding. What is the difference between the API docs in the backend repo and the web-API docs in the docs repo?

**Comment by hitohata** [comment]
@taniguchiiqqq 
Sorry, I mentioned above means the Web-API, and your concern is correct.
We haven't decided yet if we use multiple lambdas and the BFF. If we use those, each API will have a Web-API. This means that the main project will be one of those APIs and needs a web-API document.

**Comment by taniguchiiqqq** [comment]
@hitohata 
Thanks! Now I got it! I'll remember that the doc dir structure would change depending on how we make web-API.

**Pull request merged**
